#include "wasm/WasmStreamingParser.cpp"
#include "wasm/WasmTable.cpp"
#include "wasm/WasmThunks.cpp"
#include "wasm/WasmValidate.cpp"
#include "wasm/WasmWorklist.cpp"
#include "wasm/js/JSToWasm.cpp"
#include "wasm/js/JSToWasmICCallee.cpp"
#include "wasm/js/JSWebAssembly.cpp"
