#include "dfg/DFGDesiredWeakReferences.cpp"
#include "dfg/DFGDisassembler.cpp"
#include "dfg/DFGDoesGC.cpp"
#include "dfg/DFGDriver.cpp"
#include "dfg/DFGEdge.cpp"
#include "dfg/DFGEpoch.cpp"
#include "dfg/DFGFailedFinalizer.cpp"
#include "dfg/DFGFinalizer.cpp"
