#include "dfg/DFGOSRExitFuzz.cpp"
#include "dfg/DFGOSRExitJumpPlaceholder.cpp"
#include "dfg/DFGOSRExitPreparation.cpp"
#include "dfg/DFGObjectAllocationSinkingPhase.cpp"
#include "dfg/DFGObjectMaterializationData.cpp"
#include "dfg/DFGOperations.cpp"
#include "dfg/DFGPhantomInsertionPhase.cpp"
#include "dfg/DFGPhase.cpp"
