#include "wasm/js/WebAssemblyPrototype.cpp"
#include "wasm/js/WebAssemblyRuntimeErrorConstructor.cpp"
#include "wasm/js/WebAssemblyRuntimeErrorPrototype.cpp"
#include "wasm/js/WebAssemblyTableConstructor.cpp"
#include "wasm/js/WebAssemblyTablePrototype.cpp"
#include "wasm/js/WebAssemblyToJSCallee.cpp"
#include "wasm/js/WebAssemblyWrapperFunction.cpp"
