#include "runtime/AtomicsObject.cpp"
#include "runtime/BasicBlockLocation.cpp"
#include "runtime/BigIntConstructor.cpp"
#include "runtime/BigIntObject.cpp"
#include "runtime/BigIntPrototype.cpp"
#include "runtime/BooleanConstructor.cpp"
#include "runtime/BooleanObject.cpp"
#include "runtime/BooleanPrototype.cpp"
