#include "b3/air/AirEliminateDeadCode.cpp"
#include "b3/air/AirEmitShuffle.cpp"
#include "b3/air/AirFixObviousSpills.cpp"
#include "b3/air/AirFixPartialRegisterStalls.cpp"
#include "b3/air/AirFixSpillsAfterTerminals.cpp"
#include "b3/air/AirGenerate.cpp"
#include "b3/air/AirGenerated.cpp"
#include "b3/air/AirHandleCalleeSaves.cpp"
