#include "runtime/ArrayPrototype.cpp"
#include "runtime/AsyncFromSyncIteratorPrototype.cpp"
#include "runtime/AsyncFunctionConstructor.cpp"
#include "runtime/AsyncFunctionPrototype.cpp"
#include "runtime/AsyncGeneratorFunctionConstructor.cpp"
#include "runtime/AsyncGeneratorFunctionPrototype.cpp"
#include "runtime/AsyncGeneratorPrototype.cpp"
#include "runtime/AsyncIteratorPrototype.cpp"
