#include "runtime/VM.cpp"
#include "runtime/VMEntryScope.cpp"
#include "runtime/VMTraps.cpp"
#include "runtime/VarOffset.cpp"
#include "runtime/Watchdog.cpp"
#include "runtime/WeakMapConstructor.cpp"
#include "runtime/WeakMapImpl.cpp"
#include "runtime/WeakMapPrototype.cpp"
