#include "wasm/js/JSWebAssemblyTable.cpp"
#include "wasm/js/WasmToJS.cpp"
#include "wasm/js/WebAssemblyCompileErrorConstructor.cpp"
#include "wasm/js/WebAssemblyCompileErrorPrototype.cpp"
#include "wasm/js/WebAssemblyFunction.cpp"
#include "wasm/js/WebAssemblyFunctionBase.cpp"
#include "wasm/js/WebAssemblyFunctionHeapCellType.cpp"
#include "wasm/js/WebAssemblyInstanceConstructor.cpp"
