#include "runtime/JSModuleRecord.cpp"
#include "runtime/JSNativeStdFunction.cpp"
#include "runtime/JSONObject.cpp"
#include "runtime/JSObject.cpp"
#include "runtime/JSPromise.cpp"
#include "runtime/JSPromiseConstructor.cpp"
#include "runtime/JSPromisePrototype.cpp"
#include "runtime/JSPropertyNameEnumerator.cpp"
