#include "runtime/Watchdog.cpp"
#include "runtime/WeakMapConstructor.cpp"
#include "runtime/WeakMapImpl.cpp"
#include "runtime/WeakMapPrototype.cpp"
#include "runtime/WeakObjectRefConstructor.cpp"
#include "runtime/WeakObjectRefPrototype.cpp"
#include "runtime/WeakSetConstructor.cpp"
#include "runtime/WeakSetPrototype.cpp"
