#include "dfg/DFGJumpReplacement.cpp"
#include "dfg/DFGLICMPhase.cpp"
#include "dfg/DFGLazyJSValue.cpp"
#include "dfg/DFGLazyNode.cpp"
#include "dfg/DFGLiveCatchVariablePreservationPhase.cpp"
#include "dfg/DFGLivenessAnalysisPhase.cpp"
#include "dfg/DFGLoopPreHeaderCreationPhase.cpp"
#include "dfg/DFGMaximalFlushInsertionPhase.cpp"
